### ISSUE TITLE
20210411 과제 제출(이한결)

### ISSUE THREAD

**Issue by hanana1253** [ai-creatv/algorithm_PBS18#2]
프로그래머스 레벨1 달성 및 Linked List 구현 과제 파일이 담긴 주소입니다.
- 프로그래머스: 두 문제를 solution.py와 solution_test.py 속 1과 2로 나누어 작성했습니다.
- Linked List: 해결할 문제가 있어서 내일 더 보완하겠습니다.

https://github.com/hanana1253/TIL/tree/main/Algorithm/20210411%20homework

감사합니다.
이한결 드림

**Comment by ai-creatv** [comment]
간결하게 잘 구현해 주셨습니다! :)

1번 답안에서 set(nums)가 두번 사용됐는데, set(nums)는 O(n)의 시간복잡도를 가지므로, 변수로 받아서 중복을 없애시는 것이 좋습니다.

수고하셨습니다 :)
