### ISSUE TITLE
프로그래머스 level1 과제

### ISSUE THREAD

**Issue by heejung-gjt** [ai-creatv/algorithm_PBS18#4]
프로그래머스 level1 과제제출 링크입니다.
solution1과 solution2로 나누어 업로드 하였습니다.
https://github.com/heejung-gjt/Python-Algorithm/tree/master/programmers/Level1

**Comment by ai-creatv** [comment]
공부하신 내용을 깔끔하게 잘 정리하셨네요! 좋은 습관입니다 :)

1번 문제의 경우, 삼항 연산자를 쓰기에 조건문이 너무 길어지기 때문에, 일반 if문을 쓰는 것이 더 좋습니다. (가독성)

2번 문제는 while문보다는 for문을 사용해 주시면 가독성이 더 좋아집니다. 예를 들면

```python
answer = 0
for i in range(len(a)):
    answer += a[i] * b[i]
```

으로 하셔도 좋고, zip을 이용할 경우

```python
answer = 0
for x, y in zip(a, b):
    answer += x * y
```

와 같이 작성하셔도 좋습니다.

수고하셨습니다! :)

**Comment by ai-creatv** [comment]
질문해주신 초기값은 수정해서 사용하셔도 됩니다!
