### ISSUE TITLE
프로그래머스 스킬체크 과제 제출(오지윤)

### ISSUE THREAD

**Issue by Odreystella** [ai-creatv/algorithm_PBS18#6]
시간초과로 여러번 문제를 풀다가 쉬운문제가 나왔을 때 통과했습니다..
번외로 푼 문제들도 리뷰받으면 좋을 것 같아서 깃허브에 올려 두었습니다.
1, 2번은 레벨테스트 통과 문제이고, 3~6은 번외로 푼 문제입니다.
https://github.com/Odreystella/algorithm_Homework

**Comment by ai-creatv** [comment]
6개 코드 모두 깔끔하게 잘 구현해 주셨습니다! :)

5번의 경우 아래와 같이 int()를 추가해 주시면 정답이 됩니다.

```python
def solution(n):
    answer = [int(i) for i in str(n)]
    return answer[::-1]
```

수고하셨습니다 :)
