### ISSUE TITLE
프로그래머스 과제 제출 lv.1 - 김도준

### ISSUE THREAD

**Issue by downside154** [ai-creatv/algorithm_PBS18#7]
알고리즘 과제 문제 풀이 제출입니다.
https://github.com/downside154/AlgorithmExercise

exercise1.py를 검토 받고 싶습니다. ( 더 깔끔하게 작성 할 수 없을까요? )

**Comment by ai-creatv** [comment]
1번 문제를 더 깔끔하게 작성한 코드를 아래 공유드리니 참고해주세요 :) 수고하셨습니다!

```python
def solution (a, b):
    if a == b:
        return a
    if a > b:
        a, b = b, a
    return sum(range (a, b+1))
```
